### PR TITLE
change certificate of good standing lang

### PR DESCRIPTION
**Pull request by lauraGgit**
update the language per the MBS SUA's comments.

@hannahkane/ @msadakFS  can you verify that the `person` wouldn't need this message?

### CODE REVIEW

**Comment by hannahkane** [comment]
@lauraGgit - I'm +1 on the code change, but I don't understand your question about whether the person would need the message. Can you clarify, please?

**Comment by lauraGgit** [comment]
@hannahkane whether an individual applicant - vs only corps/llc would need it too

**Comment by hannahkane** [comment]
Ah, thanks for clarifying. I will have to defer to @msadakFS on that.

**Comment by lauraGgit** [comment]
@hannahkane are you ok to approve and then that can be part of PO review?

**Comment by msadakFS** [comment]
@lauraGgit I talked to a Forest level SUA this morning and she stated that it is required for both individuals and organizations, so they would both need to see the language

**Pull request merged**
